name: dump-context
description: "dump GitHub Actions context for debugging reusable workflows"

# context concept:
# https://docs.github.com/en/actions/concepts/workflows-and-actions/contexts

# context reference:
# https://docs.github.com/en/actions/reference/workflows-and-actions/contexts

# ::group:: and ::endgroup:: are GitHub Actions workflow commands
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#grouping-log-lines

inputs:
  annotate:
    default: false
    description: "Whether to add an annotation notice in the workflow"
    required: false
  env:
    default: true
    description: "Whether to dump env context"
    required: false
  github:
    default: true
    description: "Whether to dump github context"
    required: false
  context_inputs:
    default: true
    description: "Whether to dump inputs context"
    required: false
  job:
    default: true
    description: "Whether to dump job context"
    required: false
  matrix:
    default: true
    description: "Whether to dump matrix context"
    required: false
  needs:
    default: false
    description: "Whether to dump needs context"
    required: false
  runner:
    default: true
    description: "Whether to dump runner context"
    required: false
  secrets:
    default: false
    description: "Whether to dump secrets context"
    required: false
  steps:
    default: true
    description: "Whether to dump steps context"
    required: false
  strategy:
    default: true
    description: "Whether to dump strategy context"
    required: false
  vars:
    default: true
    description: "Whether to dump vars context"
    required: false

runs:
  using: "composite"
  steps:
    - name: dump context
      shell: bash
      run: |
        echo -e "Dumping context...\n"

        if [ "${{ inputs.env }}" = "true" ]; then
          echo "::group::env context:"
          echo "${{ toJson(env) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.github }}" = "true" ]; then
          echo "::group::github context:"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.context_inputs }}" = "true" ]; then
          echo "::group::inputs context:"
          echo "${{ toJson(inputs) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.job }}" = "true" ]; then
          echo "::group::job context:"
          echo "${{ toJson(job) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.matrix }}" = "true" ]; then
          echo "::group::matrix context:"
          echo "${{ toJson(matrix) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.needs }}" = "true" ]; then
          echo "::group::needs context:"
          echo "${{ toJson(needs) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.runner }}" = "true" ]; then
          echo "::group::runner context:"
          echo "${{ toJson(runner) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.secrets }}" = "true" ]; then
          echo "::group::secrets context:"
          echo "${{ toJson(secrets) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.steps }}" = "true" ]; then
          echo "::group::steps context:"
          echo "${{ toJson(steps) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.strategy }}" = "true" ]; then
          echo "::group::strategy context:"
          echo "${{ toJson(strategy) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.vars }}" = "true" ]; then
          echo "::group::vars context:"
          echo "${{ toJson(vars) }}"
          echo "::endgroup::"
        fi

        if [ "${{ inputs.annotate }}" = "true" ]; then
          echo -e "\n::notice::Context details.\n"
        fi
